### ISSUE TITLE
Error opening wows-stats-plus

### ISSUE THREAD

**Issue by phoebustam** [anmonite/wows-stats-plus#15]
Hello again, sorry to bother, but today I got another problem when I open the application. It pops up an error log in the CMD very briefly and closes itself, the program does not run. Not sure why and how this happened, but I managed to took a screenshot of the cmd and found the log file. Would you please help? Much obliged!
![Picture1](https://user-images.githubusercontent.com/6040710/57718963-3f039880-76b1-11e9-996a-82ef66094198.png)
[2019-05-14T17_28_12_827Z-debug.log](https://github.com/anmonite/wows-stats-plus/files/3179063/2019-05-14T17_28_12_827Z-debug.log)

**Comment by anmonite** [comment]
Thanks for sending the report.

I need more information about the type of browser, bat file name you executed, and also your windows version.

**Comment by phoebustam** [comment]
Hi, I think the problem has something to do with WG's server, because my WGC had the "unable to connect to content service" error, then the wows-stats-plus application crashed. Now that the WGC has returned to normal, the problem is fixed.
P.S.: My browser was Google Chrome, it was the run.bat file, and on Windows 10.

**Comment by anmonite** [comment]
Thanks for additional information.

But I think the best behavior of app is no crash exiting when WG API is unable to connect.
I will investigate this point if I have a long time to fix this issue.
