### ISSUE TITLE
not display player's ship data since wows 0.9.11 released.

### ISSUE THREAD

**Issue by anmonite** [anmonite/wows-stats-plus#24]
It can not get player's ship data from WG API without access_toke from TANKS OpenID authentication API since wows 0.9.11 released. 

No pre-announce for this API specification change by WG!

https://developers.wargaming.net/documentation/guide/principles/#access_token

OpenID authentication API: 
https://api.worldoftanks.asia/wot/auth/login/?application_id=xxxxxxxxxxxxxxxxxxxx&expires_at=1608298193&redirect_uri=https%3A%2F%2Fdevelopers.wargaming.net%2Freference%2Fall%2Fwot%2Fauth%2Flogin%2F&nofollow=1

New API calling method:
https://api.worldofwarships.asia/wows/ships/stats/?application_id=xxxxxxxxxxxxxxxxxxxx&account_id=00000000&access_token=xxxxxxxxxxxxxxxxxxxxx&language=ja&ship_id=111111111

**Comment by anmonite** [comment]
The latest my survey is my fault.
The root cause is other reason.

**Comment by phoebustam** [comment]
I was about to write a ticket here. I am a modified version of your program because I can display some extra statistics that I deemed worthy. But I am getting bunch of errors in the console. I tried with your version as well and it wasn't working either.

**Comment by anmonite** [comment]
I recognized the root cause is the error on WG API for ranked battles seasons info.

i.e.) https://api.worldofwarships.asia/wows/seasons/info/?application_id=xxxxxxxxxxxxxxx&fields=season_id
Above API is now return only error status even if you try to set any parameter combination.

So that it needs to change the code of index.js, app.js with excluding rank battle related code (affects cookie settings), and also index.html.  

But I have no time to fix this issue now...

**Comment by phoebustam** [comment]
Thanks for the findings. I have very limited knowledge in node.js/angular,js, but I do work with javascript and java at work. I will try to modify my version of wows-stats-plus and see how things goes. But considering my branch has some commits ahead as well as behind, any pull request if I shall make in the future will surely end up in conflicts.

**Comment by phoebustam** [comment]
I commented the API function that reaches for Ranked Season and hard-coded pre_rank and rank for all users as "**" and the issue has been fixed, thank you again for the findings.

**Comment by anmonite** [comment]
That's a simple way to fix this issue !
Nice work.

**Comment by anmonite** [comment]
Fixed this issue by #25 .

**Comment by anmonite** [comment]
@phoebustam @SuperContainer

Many thanks to collaborate this project!
